# Generated by Django 4.2 on 2026-01-27 19:10

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FloodAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vv_image', models.FileField(blank=True, null=True, upload_to='uploads/vv/')),
                ('vh_image', models.FileField(blank=True, null=True, upload_to='uploads/vh/')),
                ('rgb_image', models.FileField(blank=True, null=True, upload_to='uploads/rgb/')),
                ('ndvi_image', models.FileField(blank=True, null=True, upload_to='uploads/ndvi/')),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('processing_status', models.CharField(default='pending', max_length=50)),
                ('ml_accuracy', models.FloatField(blank=True, null=True)),
                ('ml_precision', models.FloatField(blank=True, null=True)),
                ('ml_recall', models.FloatField(blank=True, null=True)),
                ('ml_f1_score', models.FloatField(blank=True, null=True)),
                ('ml_iou', models.FloatField(blank=True, null=True)),
                ('best_ml_model', models.CharField(blank=True, max_length=100, null=True)),
                ('dl_accuracy', models.FloatField(blank=True, null=True)),
                ('dl_precision', models.FloatField(blank=True, null=True)),
                ('dl_recall', models.FloatField(blank=True, null=True)),
                ('dl_f1_score', models.FloatField(blank=True, null=True)),
                ('dl_iou', models.FloatField(blank=True, null=True)),
                ('predicted_rainfall_mm', models.FloatField(blank=True, null=True)),
                ('rainfall_confidence', models.FloatField(blank=True, null=True)),
                ('flood_area_km2', models.FloatField(blank=True, null=True)),
                ('flood_percentage', models.FloatField(blank=True, null=True)),
                ('flood_severity', models.CharField(blank=True, max_length=50, null=True)),
                ('flood_mask_image', models.ImageField(blank=True, null=True, upload_to='results/masks/')),
                ('overlay_image', models.ImageField(blank=True, null=True, upload_to='results/overlays/')),
                ('change_detection_image', models.ImageField(blank=True, null=True, upload_to='results/change/')),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Flood Analysis',
                'verbose_name_plural': 'Flood Analyses',
                'ordering': ['-upload_date'],
            },
        ),
    ]
