# Generated by Django 5.2.10 on 2026-03-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='floodanalysis',
            options={'ordering': ['-upload_date']},
        ),
        migrations.RenameField(
            model_name='floodanalysis',
            old_name='ml_f1_score',
            new_name='dl_dice',
        ),
        migrations.RenameField(
            model_name='floodanalysis',
            old_name='ml_accuracy',
            new_name='ml_gb_accuracy',
        ),
        migrations.RenameField(
            model_name='floodanalysis',
            old_name='ml_iou',
            new_name='ml_gb_f1_score',
        ),
        migrations.RenameField(
            model_name='floodanalysis',
            old_name='ml_precision',
            new_name='ml_gb_iou',
        ),
        migrations.RenameField(
            model_name='floodanalysis',
            old_name='ml_recall',
            new_name='ml_gb_precision',
        ),
        migrations.RemoveField(
            model_name='floodanalysis',
            name='flood_mask_image',
        ),
        migrations.RemoveField(
            model_name='floodanalysis',
            name='ndvi_image',
        ),
        migrations.RemoveField(
            model_name='floodanalysis',
            name='rgb_image',
        ),
        migrations.RemoveField(
            model_name='floodanalysis',
            name='vh_image',
        ),
        migrations.RemoveField(
            model_name='floodanalysis',
            name='vv_image',
        ),
        migrations.AddField(
            model_name='floodanalysis',
            name='comparison_image',
            field=models.ImageField(blank=True, null=True, upload_to='results/comparison/'),
        ),
        migrations.AddField(
            model_name='floodanalysis',
            name='flood_mask_dl',
            field=models.ImageField(blank=True, null=True, upload_to='results/masks_dl/'),
        ),
        migrations.AddField(
            model_name='floodanalysis',
            name='flood_mask_ml',
            field=models.ImageField(blank=True, null=True, upload_to='results/masks_ml/'),
        ),
        migrations.AddField(
            model_name='floodanalysis',
            name='ml_gb_recall',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='floodanalysis',
            name='ml_rf_accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='floodanalysis',
            name='ml_rf_f1_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='floodanalysis',
            name='ml_rf_iou',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='floodanalysis',
            name='ml_rf_precision',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='floodanalysis',
            name='ml_rf_recall',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='floodanalysis',
            name='ndvi_after',
            field=models.FileField(blank=True, null=True, upload_to='uploads/after/ndvi/'),
        ),
        migrations.AddField(
            model_name='floodanalysis',
            name='ndvi_before',
            field=models.FileField(blank=True, null=True, upload_to='uploads/before/ndvi/'),
        ),
        migrations.AddField(
            model_name='floodanalysis',
            name='processing_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='floodanalysis',
            name='rgb_after',
            field=models.FileField(blank=True, null=True, upload_to='uploads/after/rgb/'),
        ),
        migrations.AddField(
            model_name='floodanalysis',
            name='rgb_before',
            field=models.FileField(blank=True, null=True, upload_to='uploads/before/rgb/'),
        ),
        migrations.AddField(
            model_name='floodanalysis',
            name='vh_after',
            field=models.FileField(blank=True, null=True, upload_to='uploads/after/vh/'),
        ),
        migrations.AddField(
            model_name='floodanalysis',
            name='vh_before',
            field=models.FileField(blank=True, null=True, upload_to='uploads/before/vh/'),
        ),
        migrations.AddField(
            model_name='floodanalysis',
            name='vv_after',
            field=models.FileField(blank=True, null=True, upload_to='uploads/after/vv/'),
        ),
        migrations.AddField(
            model_name='floodanalysis',
            name='vv_before',
            field=models.FileField(blank=True, null=True, upload_to='uploads/before/vv/'),
        ),
    ]
