# Generated by Django 5.2.10 on 2026-03-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection_app', '0002_alter_floodanalysis_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='floodanalysis',
            options={'ordering': ['-upload_date'], 'verbose_name': 'Flood Analysis', 'verbose_name_plural': 'Flood Analyses'},
        ),
        migrations.RenameField(
            model_name='floodanalysis',
            old_name='dl_dice',
            new_name='ml_accuracy',
        ),
        migrations.RenameField(
            model_name='floodanalysis',
            old_name='ml_gb_accuracy',
            new_name='ml_f1_score',
        ),
        migrations.RenameField(
            model_name='floodanalysis',
            old_name='ml_gb_f1_score',
            new_name='ml_iou',
        ),
        migrations.RenameField(
            model_name='floodanalysis',
            old_name='ml_gb_iou',
            new_name='ml_precision',
        ),
        migrations.RenameField(
            model_name='floodanalysis',
            old_name='ml_gb_precision',
            new_name='ml_recall',
        ),
        migrations.RemoveField(
            model_name='floodanalysis',
            name='comparison_image',
        ),
        migrations.RemoveField(
            model_name='floodanalysis',
            name='flood_mask_dl',
        ),
        migrations.RemoveField(
            model_name='floodanalysis',
            name='flood_mask_ml',
        ),
        migrations.RemoveField(
            model_name='floodanalysis',
            name='ml_gb_recall',
        ),
        migrations.RemoveField(
            model_name='floodanalysis',
            name='ml_rf_accuracy',
        ),
        migrations.RemoveField(
            model_name='floodanalysis',
            name='ml_rf_f1_score',
        ),
        migrations.RemoveField(
            model_name='floodanalysis',
            name='ml_rf_iou',
        ),
        migrations.RemoveField(
            model_name='floodanalysis',
            name='ml_rf_precision',
        ),
        migrations.RemoveField(
            model_name='floodanalysis',
            name='ml_rf_recall',
        ),
        migrations.RemoveField(
            model_name='floodanalysis',
            name='ndvi_after',
        ),
        migrations.RemoveField(
            model_name='floodanalysis',
            name='ndvi_before',
        ),
        migrations.RemoveField(
            model_name='floodanalysis',
            name='processing_time',
        ),
        migrations.RemoveField(
            model_name='floodanalysis',
            name='rgb_after',
        ),
        migrations.RemoveField(
            model_name='floodanalysis',
            name='rgb_before',
        ),
        migrations.RemoveField(
            model_name='floodanalysis',
            name='vh_after',
        ),
        migrations.RemoveField(
            model_name='floodanalysis',
            name='vh_before',
        ),
        migrations.RemoveField(
            model_name='floodanalysis',
            name='vv_after',
        ),
        migrations.RemoveField(
            model_name='floodanalysis',
            name='vv_before',
        ),
        migrations.AddField(
            model_name='floodanalysis',
            name='flood_mask_image',
            field=models.ImageField(blank=True, null=True, upload_to='results/masks/'),
        ),
        migrations.AddField(
            model_name='floodanalysis',
            name='ndvi_image',
            field=models.FileField(blank=True, null=True, upload_to='uploads/ndvi/'),
        ),
        migrations.AddField(
            model_name='floodanalysis',
            name='rgb_image',
            field=models.FileField(blank=True, null=True, upload_to='uploads/rgb/'),
        ),
        migrations.AddField(
            model_name='floodanalysis',
            name='vh_image',
            field=models.FileField(blank=True, null=True, upload_to='uploads/vh/'),
        ),
        migrations.AddField(
            model_name='floodanalysis',
            name='vv_image',
            field=models.FileField(blank=True, null=True, upload_to='uploads/vv/'),
        ),
    ]
